### PR TITLE
let users (me) pet the cat

### PR DESCRIPTION
**Pull request by l-koehler**
important pr!!
lets users pet the cat while it is eeping

### CODE REVIEW

**Comment by dualfighter1** [comment]
holy fuck that shit is incredible, am i ok to steal it for my site :0

**Comment by l-koehler** [comment]
yes! sadly this pr only has heart sprites for the maia kitten, youll need to add these to oneko.gif yourself

**Comment by dualfighter1** [comment]
yeah makes sense, thanks for letting me use it :3

**Comment by nyancrimew** [comment]
finally remembered about this and cherry picked it into main!

**Pull request closed without merging**
